theme: jekyll-theme-architect
title: [Transitive Network]
description: [Tokenless IOU Credit Network in Ethereum]
show_downloads: false
github: 
  is_project_page: false
  is_user_page: true
  owner_url: "https://github.com/pedrorechez"
plugins:
    - jekyll-sitemap
